"""Typed intermediate representation for AgentCo-Op.

Everything else in the system compiles against these types. They are kept in
one place, with no dependencies on execution, LLMs, or I/O, so that the
compiler, the diagnoser, the repairer, and the evaluator all talk about the
same objects.
"""

from agentcoop.ir.artifacts import (
    Artifact,
    ArtifactType,
    Compatibility,
    CompatibilityReport,
    Converter,
    FacetSet,
    TypeRegistry,
    build_lineage_index,
    lineage_of,
    validate_payload,
)
from agentcoop.ir.capability import (
    BehaviorContract,
    CapabilityCard,
    CertificationLevel,
    ComponentKind,
    ComponentLibrary,
    CostProfile,
    EmpiricalRecord,
    EnvironmentContract,
    FailureSignature,
    IOContract,
    ProbeOutcome,
    ReliabilityPosterior,
    TrustMetadata,
)
from agentcoop.ir.checks import (
    CheckLevel,
    CheckReport,
    CheckResult,
    CheckStatus,
    SignalSource,
)
from agentcoop.ir.dossier import (
    Direction,
    EvaluatorAvailability,
    EvidenceChainRequirement,
    HumanReviewCondition,
    Invariant,
    Preference,
    ResourceLimits,
    RiskLevel,
    Subgoal,
    TaskEvidenceDossier,
)
from agentcoop.ir.evidence import (
    Alternative,
    DecisionKind,
    DesignEvidenceRecord,
    EvidenceItem,
    EvidenceKind,
    EvidenceLedger,
    EvidenceStrength,
    asserted_evidence,
    capability_evidence,
    coordination_evidence,
    outcome_evidence,
    requirement_evidence,
)
from agentcoop.ir.faults import (
    FAULT_TAXONOMY,
    BlameTarget,
    Diagnosis,
    FaultClass,
    FaultHypothesis,
    FaultSpec,
    RepairTier,
)
from agentcoop.ir.preference import (
    JudgeCallRecord,
    JudgeCallStatus,
    MetaCriterion,
    MetaRubric,
    ObservationStatus,
    OrderedPairJudgment,
    PairRubric,
    PairwisePreferenceObservation,
    PairwiseVerdict,
    PanelAttemptRecord,
    PanelAttemptStatus,
    PolicyObservationStatus,
    PolicyPreferenceObservation,
    PreferenceArchive,
    RubricCriterion,
    RubricRef,
    Scorepad,
    ScorepadEntry,
    VerbosityMode,
    VerbosityPolicy,
    normalize_order_swaps,
)
from agentcoop.ir.utility import (
    MAXIMIZE,
    Objective,
    SelectionPolicy,
    SynergyReport,
    UtilityVector,
    dominates,
    hypervolume,
    pareto_front,
    select,
    synergy,
)
from agentcoop.ir.workflow import (
    Atomic,
    CompiledWorkflow,
    ExecEdge,
    ExecGraph,
    ExecNode,
    Fallback,
    HumanGate,
    Join,
    Parallel,
    RepairPolicy,
    Sequence,
    Verify,
    WorkflowTerm,
    atomics,
    find_term,
    iter_terms,
    lower,
    replace_term,
)

__all__ = [
    # artifacts
    "Artifact",
    "ArtifactType",
    "Compatibility",
    "CompatibilityReport",
    "Converter",
    "FacetSet",
    "TypeRegistry",
    "build_lineage_index",
    "lineage_of",
    "validate_payload",
    # capability
    "BehaviorContract",
    "CapabilityCard",
    "CertificationLevel",
    "ComponentKind",
    "ComponentLibrary",
    "CostProfile",
    "EmpiricalRecord",
    "EnvironmentContract",
    "FailureSignature",
    "IOContract",
    "ProbeOutcome",
    "ReliabilityPosterior",
    "TrustMetadata",
    # checks
    "CheckLevel",
    "CheckReport",
    "CheckResult",
    "CheckStatus",
    "SignalSource",
    # dossier
    "Direction",
    "EvaluatorAvailability",
    "EvidenceChainRequirement",
    "HumanReviewCondition",
    "Invariant",
    "Preference",
    "ResourceLimits",
    "RiskLevel",
    "Subgoal",
    "TaskEvidenceDossier",
    # evidence
    "Alternative",
    "DecisionKind",
    "DesignEvidenceRecord",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceLedger",
    "EvidenceStrength",
    "asserted_evidence",
    "capability_evidence",
    "coordination_evidence",
    "outcome_evidence",
    "requirement_evidence",
    # faults
    "FAULT_TAXONOMY",
    "BlameTarget",
    "Diagnosis",
    "FaultClass",
    "FaultHypothesis",
    "FaultSpec",
    "RepairTier",
    # preference protocol
    "JudgeCallRecord",
    "JudgeCallStatus",
    "MetaCriterion",
    "MetaRubric",
    "ObservationStatus",
    "OrderedPairJudgment",
    "PairRubric",
    "PairwisePreferenceObservation",
    "PairwiseVerdict",
    "PanelAttemptRecord",
    "PanelAttemptStatus",
    "PolicyObservationStatus",
    "PolicyPreferenceObservation",
    "PreferenceArchive",
    "RubricCriterion",
    "RubricRef",
    "Scorepad",
    "ScorepadEntry",
    "VerbosityMode",
    "VerbosityPolicy",
    "normalize_order_swaps",
    # utility
    "MAXIMIZE",
    "Objective",
    "SelectionPolicy",
    "SynergyReport",
    "UtilityVector",
    "dominates",
    "hypervolume",
    "pareto_front",
    "select",
    "synergy",
    # workflow
    "Atomic",
    "CompiledWorkflow",
    "ExecEdge",
    "ExecGraph",
    "ExecNode",
    "Fallback",
    "HumanGate",
    "Join",
    "Parallel",
    "RepairPolicy",
    "Sequence",
    "Verify",
    "WorkflowTerm",
    "atomics",
    "find_term",
    "iter_terms",
    "lower",
    "replace_term",
]
