"""Sandbox builder.

Turns a `RepoProfile` (or a hand-written `SandboxSpec`) into a
Dockerfile + docker-compose service definition + smoke-test script. By
default the artifacts are written to disk only (`dry_run=True`) so the
case study is exercisable on a host without a Docker daemon. When
Docker is available the same module can drive `docker build` /
`docker compose up`.

This module is **additive**: it does not modify any existing AgentCo-Op
behaviour.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

from agentcoop.core.repo_profile import RepoProfile


StrategyT = Literal["conda", "uv", "pip", "nix", "docker_native"]


class SandboxSpec(BaseModel):
    """User-overridable knobs for one sandbox.

    Most fields default to values inferred from the `RepoProfile`. The
    spec is what the case-study request YAML can override per agent.
    """

    model_config = ConfigDict(extra="allow")

    name: str
    repo_url: str
    strategy: StrategyT = "pip"
    base_image: str = "python:3.11-slim"
    python_version: str | None = None
    extra_apt_packages: list[str] = Field(default_factory=list)
    extra_pip_packages: list[str] = Field(default_factory=list)
    requires_api_key: bool = False
    api_key_envs: list[str] = Field(default_factory=list)
    extra_env: dict[str, str] = Field(default_factory=dict)
    workdir: str = "/workspace"
    wrapper_path: str | None = None
    install_cmds: list[str] = Field(default_factory=list)
    smoke_test_python: str = "import sys; print('smoke-test-ok')"
    network: Literal["none", "bridge", "allowlist"] = "bridge"
    cpus: int = 4
    memory_gb: int = 8
    gpu: bool = False


@dataclass
class BuildResult:
    spec: SandboxSpec
    dockerfile_path: Path
    smoke_test_path: Path
    image_built: bool
    smoke_ok: bool | None
    notes: list[str]


# ---------------------------------------------------------------------------
# Spec inference from RepoProfile
# ---------------------------------------------------------------------------


def spec_from_profile(
    profile: RepoProfile,
    *,
    name: str | None = None,
    overrides: dict | None = None,
) -> SandboxSpec:
    overrides = overrides or {}
    name = name or profile.repo_name

    # Pick the most reliable installer the profile reports.
    strategy: StrategyT
    if "conda" in profile.package_managers:
        strategy = "conda"
    elif "uv" in profile.package_managers or "pep621" in profile.package_managers:
        strategy = "uv"
    elif "pip" in profile.package_managers or "setuptools" in profile.package_managers:
        strategy = "pip"
    elif "nix" in profile.package_managers:
        strategy = "nix"
    else:
        strategy = "pip"

    py = profile.python_version_hint or ("3.11" if strategy in ("uv", "pip") else None)
    base_image = (
        f"python:{py}-slim"
        if py and strategy in ("uv", "pip")
        else "mambaorg/micromamba:1.5.8"
        if strategy == "conda"
        else "python:3.11-slim"
    )

    spec = SandboxSpec(
        name=name,
        repo_url=profile.repo_url,
        strategy=strategy,
        base_image=base_image,
        python_version=py,
        requires_api_key=profile.requires_api_key,
        api_key_envs=list(profile.api_key_envs),
    )
    if overrides:
        spec = spec.model_copy(update=overrides)
    return spec


# ---------------------------------------------------------------------------
# Dockerfile + smoke-test generation
# ---------------------------------------------------------------------------


def render_dockerfile(spec: SandboxSpec, profile: RepoProfile | None = None) -> str:
    apt = " ".join(["git", "build-essential", "curl", "ca-certificates", *spec.extra_apt_packages])
    install_block = _install_block(spec, profile)
    extra_pip = (
        "\nRUN pip install --no-cache-dir "
        + " ".join(spec.extra_pip_packages)
        if spec.extra_pip_packages
        else ""
    )
    api_env_block = (
        "\n".join(f"ENV {e}=" for e in spec.api_key_envs)
        if spec.api_key_envs
        else "# no api keys required"
    )
    extra_env_block = (
        "\n".join(f"ENV {k}={v}" for k, v in spec.extra_env.items())
        if spec.extra_env
        else "# no extra env"
    )

    if spec.strategy == "conda":
        dockerfile = textwrap.dedent(
            f"""\
            # generated by agentcoop SandboxBuilder ({spec.strategy} strategy)
            FROM {spec.base_image}

            USER root
            RUN apt-get update && apt-get install -y --no-install-recommends \\
                {apt} \\
                && rm -rf /var/lib/apt/lists/*

            WORKDIR {spec.workdir}
            RUN git clone --depth 1 --recurse-submodules {spec.repo_url} {spec.workdir}/repo
            WORKDIR {spec.workdir}/repo

            {install_block}{extra_pip}

            {api_env_block}
            {extra_env_block}

            WORKDIR {spec.workdir}
            CMD ["python", "{spec.wrapper_path or '/workspace/wrappers/' + spec.name + '_worker.py'}", "--serve"]
            """
        )
    elif spec.strategy == "uv":
        dockerfile = textwrap.dedent(
            f"""\
            # generated by agentcoop SandboxBuilder ({spec.strategy} strategy)
            FROM {spec.base_image}

            RUN apt-get update && apt-get install -y --no-install-recommends \\
                {apt} \\
                && rm -rf /var/lib/apt/lists/*
            RUN pip install --no-cache-dir uv

            WORKDIR {spec.workdir}
            RUN git clone --depth 1 --recurse-submodules {spec.repo_url} {spec.workdir}/repo
            WORKDIR {spec.workdir}/repo

            {install_block}{extra_pip}

            {api_env_block}
            {extra_env_block}

            WORKDIR {spec.workdir}
            CMD ["python", "{spec.wrapper_path or '/workspace/wrappers/' + spec.name + '_worker.py'}", "--serve"]
            """
        )
    else:  # pip / nix / fallback
        dockerfile = textwrap.dedent(
            f"""\
            # generated by agentcoop SandboxBuilder ({spec.strategy} strategy)
            FROM {spec.base_image}

            RUN apt-get update && apt-get install -y --no-install-recommends \\
                {apt} \\
                && rm -rf /var/lib/apt/lists/*

            WORKDIR {spec.workdir}
            RUN git clone --depth 1 --recurse-submodules {spec.repo_url} {spec.workdir}/repo
            WORKDIR {spec.workdir}/repo

            {install_block}{extra_pip}

            {api_env_block}
            {extra_env_block}

            WORKDIR {spec.workdir}
            CMD ["python", "{spec.wrapper_path or '/workspace/wrappers/' + spec.name + '_worker.py'}", "--serve"]
            """
        )
    return dockerfile


def _install_block(spec: SandboxSpec, profile: RepoProfile | None) -> str:
    if spec.install_cmds:
        return "\n".join(f"RUN {c}" for c in spec.install_cmds)
    files = set((profile.environment_files if profile else []) or [])
    if spec.strategy == "conda" and ("environment.yml" in files or "environment.yaml" in files):
        env_file = "environment.yml" if "environment.yml" in files else "environment.yaml"
        env_name = (spec.name or "agentcoop").lower().replace(" ", "_")
        return (
            f"RUN micromamba create -y -n {env_name} -f {env_file} && micromamba clean -a -y\n"
            f"SHELL [\"micromamba\", \"run\", \"-n\", \"{env_name}\", \"/bin/bash\", \"-lc\"]\n"
            "RUN pip install -e ."
        )
    if spec.strategy == "uv" and ("pyproject.toml" in files or "uv.lock" in files):
        return "RUN uv sync && uv pip install -e ."
    if "requirements.txt" in files:
        return "RUN pip install --no-cache-dir -r requirements.txt && pip install -e . || true"
    if "pyproject.toml" in files:
        return "RUN pip install --no-cache-dir ."
    if "setup.py" in files or "setup.cfg" in files:
        return "RUN pip install --no-cache-dir ."
    return "# no canonical install file detected; user-provided install_cmds will run via SandboxSpec"


def render_compose(specs: Iterable[SandboxSpec], *, project_name: str = "agentcoop") -> str:
    services_block: list[str] = []
    for s in specs:
        env_lines: list[str] = []
        for e in s.api_key_envs:
            env_lines.append(f"      {e}: ${{{e}}}")
        for k, v in s.extra_env.items():
            env_lines.append(f"      {k}: {v}")
        env_block = "\n".join(env_lines) if env_lines else "      # (none)"
        services_block.append(textwrap.dedent(
            f"""\
              {s.name}:
                build:
                  context: ..
                  dockerfile: docker/Dockerfile.{s.name}
                image: {project_name}-{s.name}:case-study
                environment:
            {env_block}
                volumes:
                  - ../data:{s.workdir}/data:ro
                  - ../artifacts:{s.workdir}/artifacts:rw
                  - ../traces:{s.workdir}/traces:rw
                  - ../wrappers:{s.workdir}/wrappers:ro
                command: ["python", "{s.wrapper_path or s.workdir + '/wrappers/' + s.name + '_worker.py'}", "--serve"]
            """
        ))
    return "services:\n" + "\n".join(services_block)


def render_smoke_test(spec: SandboxSpec) -> str:
    return textwrap.dedent(
        f"""\
        \"\"\"Smoke test for the {spec.name} sandbox image.

        Generated by agentcoop SandboxBuilder. The intent is to confirm that the
        wrapper module imports, that the most common scientific Python deps load,
        and (optionally) that the API key env var is present. A real CI would also
        invoke the wrapper's `--smoke` mode.
        \"\"\"

        import importlib
        import os
        import sys

        ok = True
        for mod in ("agentcoop", "json"):
            try:
                importlib.import_module(mod)
            except Exception as exc:
                print(f\"FAIL: import {{mod}} -> {{exc}}\", file=sys.stderr)
                ok = False

        for env_var in {spec.api_key_envs!r}:
            if not os.environ.get(env_var):
                print(f\"WARN: env var {{env_var}} is not set\", file=sys.stderr)

        print({spec.name!r}, \"smoke-test\", \"ok\" if ok else \"failed\")
        sys.exit(0 if ok else 1)
        """
    )


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


class SandboxBuilder:
    """Generates Dockerfile + smoke-test for one sandbox; optionally builds it."""

    def __init__(
        self,
        out_dir: str | Path,
        *,
        project_name: str = "agentcoop",
    ) -> None:
        self.out_dir = Path(out_dir).expanduser().resolve()
        self.project_name = project_name
        (self.out_dir / "docker").mkdir(parents=True, exist_ok=True)
        (self.out_dir / "wrappers").mkdir(parents=True, exist_ok=True)
        (self.out_dir / "manifests").mkdir(parents=True, exist_ok=True)

    def write_dockerfile(self, spec: SandboxSpec, profile: RepoProfile | None = None) -> Path:
        path = self.out_dir / "docker" / f"Dockerfile.{spec.name}"
        path.write_text(render_dockerfile(spec, profile), encoding="utf-8")
        return path

    def write_smoke_test(self, spec: SandboxSpec) -> Path:
        path = self.out_dir / "docker" / f"smoke_{spec.name}.py"
        path.write_text(render_smoke_test(spec), encoding="utf-8")
        return path

    def write_compose(self, specs: list[SandboxSpec]) -> Path:
        path = self.out_dir / "docker" / "docker-compose.yml"
        path.write_text(render_compose(specs, project_name=self.project_name), encoding="utf-8")
        return path

    def build(
        self,
        spec: SandboxSpec,
        profile: RepoProfile | None = None,
        *,
        dry_run: bool = True,
        timeout_s: int = 1200,
    ) -> BuildResult:
        notes: list[str] = []
        df_path = self.write_dockerfile(spec, profile)
        st_path = self.write_smoke_test(spec)
        if dry_run or not _docker_available():
            if not _docker_available():
                notes.append("docker daemon not available; sandbox spec written for later build")
            return BuildResult(
                spec=spec,
                dockerfile_path=df_path,
                smoke_test_path=st_path,
                image_built=False,
                smoke_ok=None,
                notes=notes,
            )
        # Real build path (only reached when Docker is up + dry_run=False).
        # Docker tags must be lowercase — repo names like `TissueAgent`
        # need normalising before being used as a tag component.
        tag = f"{self.project_name}-{spec.name.lower()}:case-study"
        try:
            subprocess.run(
                ["docker", "build", "-f", str(df_path), "-t", tag, str(self.out_dir.parent)],
                check=True, timeout=timeout_s, capture_output=True, text=True,
            )
            notes.append(f"image built: {tag}")
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
            notes.append(f"docker build failed: {getattr(exc, 'stderr', '') or str(exc)}")
            return BuildResult(spec, df_path, st_path, False, None, notes)
        # Smoke test
        try:
            r = subprocess.run(
                ["docker", "run", "--rm", tag, "python", "/opt/smoke_test.py"],
                check=False, timeout=120, capture_output=True, text=True,
            )
            ok = (r.returncode == 0)
            notes.append(f"smoke: returncode={r.returncode}; stdout={r.stdout.strip()[:200]}")
            return BuildResult(spec, df_path, st_path, True, ok, notes)
        except subprocess.TimeoutExpired:
            notes.append("smoke timeout")
            return BuildResult(spec, df_path, st_path, True, False, notes)


def _docker_available() -> bool:
    if shutil.which("docker") is None:
        return False
    try:
        r = subprocess.run(
            ["docker", "info"], capture_output=True, text=True, timeout=5
        )
        return r.returncode == 0
    except Exception:
        return False


__all__ = [
    "SandboxSpec",
    "BuildResult",
    "SandboxBuilder",
    "spec_from_profile",
    "render_dockerfile",
    "render_compose",
    "render_smoke_test",
]
